#!/usr/bin/env perl
use Socket;
use IO::Handle;

socket(SOCK, AF_INET, SOCK_STREAM, getprotobyname("tcp"));
my $addr = sockaddr_in(3000, INADDR_ANY);
bind(SOCK, $addr);

listen(SOCK, SOMAXCONN);

while(1)
{
    next unless my $addr1 = accept(S, SOCK);
    while(<S>)
    {
        print($_);
    }
    close S;
}
